# Generated by Django 2.2.24 on 2021-09-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210928_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('firstmiddle', models.CharField(max_length=150)),
                ('casenumber', models.CharField(max_length=100)),
                ('judge', models.CharField(max_length=100)),
                ('psrwriter', models.CharField(max_length=200)),
                ('prosecuter', models.CharField(max_length=200)),
                ('attorney', models.CharField(max_length=200)),
                ('closingauthor', models.CharField(max_length=200)),
                ('statue', models.CharField(max_length=500)),
                ('pleatype', models.CharField(max_length=100)),
                ('unfiled924c', models.CharField(max_length=100)),
                ('rangelow', models.IntegerField()),
                ('rangehigh', models.IntegerField()),
                ('mandatoryminimummonths', models.IntegerField()),
                ('sentenceimposed', models.IntegerField()),
                ('supervisedrelease', models.IntegerField()),
                ('probation', models.IntegerField()),
                ('cooperationreductionpercentage', models.IntegerField()),
                ('courtrejectedinitialbindingplea', models.CharField(max_length=50)),
                ('pretrialrelease', models.CharField(max_length=100)),
                ('appealwaiver', models.CharField(max_length=50)),
                ('restitution', models.CharField(max_length=50)),
                ('plantoappeal', models.CharField(max_length=50)),
                ('motionsfiled', models.CharField(max_length=200)),
                ('motionswon', models.CharField(max_length=200)),
                ('psrobjectionsfiled', models.CharField(max_length=50)),
                ('psrobjectionswon', models.CharField(max_length=50)),
                ('sentencingmemofiled', models.CharField(max_length=50)),
                ('cooperation', models.CharField(max_length=50)),
                ('chargebargainaffectingsentencing', models.CharField(max_length=50)),
                ('variance', models.CharField(max_length=50)),
                ('criminalhistorycategory', models.CharField(max_length=50)),
                ('cctostate', models.CharField(max_length=50)),
                ('cctofederal', models.CharField(max_length=50)),
                ('mandatoryminimumimposed', models.CharField(max_length=50)),
                ('adjustedoffenselevel', models.IntegerField()),
                ('eightfiveone', models.CharField(max_length=50)),
                ('ninetwofoure', models.CharField(max_length=50)),
                ('fourbonepointone', models.CharField(max_length=50)),
                ('expertemployed', models.CharField(max_length=50)),
                ('investigatorinterviewedwitness', models.CharField(max_length=50)),
                ('courtfollowedrecommendationofnonbindingpleaagreement', models.CharField(max_length=50)),
                ('clientvisits', models.IntegerField()),
                ('closingdate', models.DateTimeField(blank=True, null=True)),
                ('special', models.CharField(max_length=200)),
                ('caselength', models.IntegerField()),
                ('formversion', models.CharField(max_length=50)),
                ('mf', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
