# Generated by Django 2.2.24 on 2021-10-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dframe_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dframe',
            name='adjustedoffenselevel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='caselength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='clientvisits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='cooperationreductionpercentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='mandatoryminimummonths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='probation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='rangehigh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='rangelow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='sentenceimposed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dframe',
            name='supervisedrelease',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
