# Generated by Django 2.2.24 on 2022-01-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211007_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='dframe',
            name='birthplace',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='children',
            field=models.CharField(default='unknown', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='cur_in_school',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='cur_student_loans',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dframe',
            name='education',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='gender',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='housingassistance',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='intake_attorney',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='intake_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dframe',
            name='intake_filename',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='intake_interviewer',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='interpreter',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='ksx_num',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='literate',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='mother_education',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='race',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='race_notes',
            field=models.CharField(default='unknown', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='religion',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='sec8',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='spouse',
            field=models.CharField(default='unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='status',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dframe',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
